"""droits des gestionnaires

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 12:24:15.749391
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('center_members', sa.Column('permissions', sa.JSON(), server_default='[]', nullable=False))
    # Les gestionnaires existants conservent les droits qu'ils avaient jusqu'ici
    # (tout sauf la gestion de l'équipe et l'annulation des lavages).
    op.execute(
        "UPDATE center_members SET permissions = '[\"manage_washers\", \"manage_catalog\", \"manage_rewards\", "
        "\"view_reports\", \"adjust_points\", \"manage_settings\"]' WHERE role = 'manager'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('center_members', 'permissions')
    # ### end Alembic commands ###
