"""paiement lavage recompense points

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 18:47:21.641172
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Nouveau type de mouvement de points : règlement d'un lavage en points
    op.execute("ALTER TYPE transactiontype ADD VALUE IF NOT EXISTS 'wash_payment'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_vehicle_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reward_id', 'vehicle_type_id')
    )
    op.create_index(op.f('ix_reward_vehicle_costs_reward_id'), 'reward_vehicle_costs', ['reward_id'], unique=False)
    op.add_column('centers', sa.Column('points_payment_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pricing_rules', sa.Column('points_price', sa.Integer(), nullable=True))
    op.add_column('redemptions', sa.Column('vehicle_type_id', sa.Integer(), nullable=True))
    op.add_column('redemptions', sa.Column('wash_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_redemptions_wash_id', 'redemptions', 'washes', ['wash_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_redemptions_vehicle_type_id', 'redemptions', 'vehicle_types', ['vehicle_type_id'], ['id'], ondelete='SET NULL')
    op.add_column('rewards', sa.Column('service_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_rewards_service_type_id', 'rewards', 'service_types', ['service_type_id'], ['id'], ondelete='SET NULL')
    op.add_column('washes', sa.Column('payment_method', sa.String(length=16), server_default='standard', nullable=False))
    op.add_column('washes', sa.Column('points_spent', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Note : PostgreSQL ne permet pas de retirer une valeur d'enum ; 'wash_payment' reste déclarée.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('washes', 'points_spent')
    op.drop_column('washes', 'payment_method')
    op.drop_constraint('fk_rewards_service_type_id', 'rewards', type_='foreignkey')
    op.drop_column('rewards', 'service_type_id')
    op.drop_constraint('fk_redemptions_vehicle_type_id', 'redemptions', type_='foreignkey')
    op.drop_constraint('fk_redemptions_wash_id', 'redemptions', type_='foreignkey')
    op.drop_column('redemptions', 'wash_id')
    op.drop_column('redemptions', 'vehicle_type_id')
    op.drop_column('pricing_rules', 'points_price')
    op.drop_column('centers', 'points_payment_enabled')
    op.drop_index(op.f('ix_reward_vehicle_costs_reward_id'), table_name='reward_vehicle_costs')
    op.drop_table('reward_vehicle_costs')
    # ### end Alembic commands ###
